# Generated by Django 2.2.6 on 2020-01-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=35)),
                ('Edition', models.IntegerField()),
                ('AuthorName', models.CharField(max_length=25)),
                ('Publication', models.CharField(max_length=25)),
                ('BookCategory', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
