# Generated by Django 2.2.6 on 2020-01-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
